export type Demand = {
	id: string;
	codeRequisition: string;
	codePosition: string;
	myHireId: string;
	creationDate: string;
	positionStartDate: string;
	accountName: string;
	codeCountry: string;
	location: string;
	roleList: string;
	skillList: string;
	projectName: string;
	demandCreatorName: string;
	demandRequestName: string;
	originatorName: string;
	recruiter: string;
	recruitmentStartDate: string;
	localGrade: string;
	bu: string;
	roleNotes: string;
};
